import { Providers } from '@/components/Providers';
import { AuthInitializer } from '@/components/layout/AuthInitializer';
import { Header } from '@/components/layout/Header';
import { ReactQueryClientProvider } from '@/components/layout/ReactQueryClientProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryClientProvider>
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <Providers>
                        <AuthInitializer />
                        <Header />
                        {children}
                    </Providers>
                </body>
            </html>
        </ReactQueryClientProvider>
    );
}
